-- SGF v4.0 - ESQUEMA ORACLE (UNICA FUENTE DE VERDAD)

CREATE TABLE SGF_USUARIOS (
    ID              VARCHAR2(36)    PRIMARY KEY,
    USERNAME        VARCHAR2(50)    NOT NULL UNIQUE,
    NAME            VARCHAR2(200)   NOT NULL,
    ROLE            VARCHAR2(20)    DEFAULT 'usuario' NOT NULL CHECK (ROLE IN ('admin', 'usuario')),
    PASSWORD_HASH   VARCHAR2(255)   NOT NULL,
    ACTIVE          NUMBER(1)       DEFAULT 1 NOT NULL CHECK (ACTIVE IN (0, 1)),
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE SGF_FACTURAS (
    ID                  VARCHAR2(36)    PRIMARY KEY,
    CLIENTE             VARCHAR2(500)   NOT NULL,
    CUENTA              VARCHAR2(500),
    NUMERO_CLIENTE      VARCHAR2(50),
    NUMERO_CUENTA       VARCHAR2(50),
    NO_FACTURA          VARCHAR2(50),
    FECHA_EMISION       VARCHAR2(30),
    FECHA_VENCIMIENTO   VARCHAR2(30),
    PERIODO_CONSUMO     VARCHAR2(60),
    CODIGO_PAGO         VARCHAR2(30),
    MONEDA              VARCHAR2(10)    DEFAULT 'CUP',
    NIT                 VARCHAR2(30),
    CUOTA               NUMBER(18,4)    DEFAULT 0,
    CONSUMO             NUMBER(18,4)    DEFAULT 0,
    COMISION            NUMBER(18,4)    DEFAULT 0,
    IMPUESTO            NUMBER(18,4)    DEFAULT 0,
    TOTAL               NUMBER(18,4)    DEFAULT 0,
    TOTAL_PAGAR         NUMBER(18,4)    DEFAULT 0,
    ESTADO              VARCHAR2(20)    DEFAULT 'pendiente' CHECK (ESTADO IN ('procesado', 'pendiente', 'error')),
    PARSER              VARCHAR2(50),
    OCR_CONFIDENCE      NUMBER(5,2)     DEFAULT 0,
    OCR_DURATION        NUMBER(10)      DEFAULT 0,
    ARCHIVO             VARCHAR2(500),
    TEXTO_OCR           CLOB,
    USER_ID             VARCHAR2(36)    NOT NULL REFERENCES SGF_USUARIOS(ID),
    CREATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE SGF_SERVICIOS (
    ID                  VARCHAR2(36)    PRIMARY KEY,
    FACTURA_ID          VARCHAR2(36)    NOT NULL REFERENCES SGF_FACTURAS(ID) ON DELETE CASCADE,
    NUMERO_SERVICIO     VARCHAR2(50)    NOT NULL,
    CUOTA               NUMBER(18,4)    DEFAULT 0,
    CONSUMO             NUMBER(18,4)    DEFAULT 0,
    COMISION            NUMBER(18,4)    DEFAULT 0,
    IMPUESTO            NUMBER(18,4)    DEFAULT 0,
    IMPORTE             NUMBER(18,4)    DEFAULT 0
);

CREATE TABLE SGF_LOGS (
    ID              VARCHAR2(36)    PRIMARY KEY,
    USER_ID         VARCHAR2(36)    REFERENCES SGF_USUARIOS(ID),
    ACCION          VARCHAR2(100)   NOT NULL,
    ENTIDAD         VARCHAR2(100),
    ENTIDAD_ID      VARCHAR2(36),
    LEVEL           VARCHAR2(10)    DEFAULT 'info' CHECK (LEVEL IN ('info', 'warn', 'error')),
    DETALLES        VARCHAR2(4000),
    IP_ADDRESS      VARCHAR2(50),
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE SGF_SESIONES (
    ID              VARCHAR2(36)    PRIMARY KEY,
    USER_ID         VARCHAR2(36)    NOT NULL REFERENCES SGF_USUARIOS(ID),
    SESSION_TOKEN   VARCHAR2(255)   NOT NULL UNIQUE,
    MACHINE_ID      VARCHAR2(200),
    IP_ADDRESS      VARCHAR2(50),
    ACTIVE          NUMBER(1)       DEFAULT 1 CHECK (ACTIVE IN (0, 1)),
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    EXPIRES_AT      TIMESTAMP       NOT NULL,
    ENDED_AT        TIMESTAMP
);

CREATE INDEX IDX_FACTURAS_USER_ID ON SGF_FACTURAS(USER_ID);
CREATE INDEX IDX_FACTURAS_ESTADO ON SGF_FACTURAS(ESTADO);
CREATE INDEX IDX_FACTURAS_NO_FACTURA ON SGF_FACTURAS(NO_FACTURA);
CREATE INDEX IDX_FACTURAS_CREATED_AT ON SGF_FACTURAS(CREATED_AT);
CREATE INDEX IDX_SERVICIOS_FACTURA_ID ON SGF_SERVICIOS(FACTURA_ID);
CREATE INDEX IDX_LOGS_USER_ID ON SGF_LOGS(USER_ID);
CREATE INDEX IDX_LOGS_CREATED_AT ON SGF_LOGS(CREATED_AT);
CREATE INDEX IDX_SESIONES_USER_ID ON SGF_SESIONES(USER_ID);
CREATE INDEX IDX_SESIONES_TOKEN ON SGF_SESIONES(SESSION_TOKEN);
